---
title: "Create Pseudo-Package"
bibliography: [../../inst/REFERENCES.bib]
biblio-style: apalike
link-citations: yes
editor_options: 
  markdown: 
    wrap: 80
---

<!-- One line about what the function does -->

`create_pseudo_package` creates a template project masqueraded as an R package.
That means, we develop the R project in an R package-like structure.

1.  The advantages of developing an R project as an R package:

    -   aaa
    -   vvv

2.  The differences between developing an R project and an R package:

    -   sss
    -   www

-   Not just reproducible research

```{r, include = FALSE}
source(file.path(usethis::proj_get(), "vignettes",  "_common.R"))
path <- fs::path_tidy(file.path(tempdir(), "template.project"))
fs::dir_create(path, recurse = TRUE)
```

## Creating a Standardized Project

```{r, echo=TRUE, eval=FALSE}
usethis2::create_pseudo_package(path = tempdir())
```

```{r usethis2-create_project, results='hide'}
usethis:::proj_set_(path) 
usethis::create_package(path, open = FALSE)
usethis::use_testthat()
```

```{r, results='markup'}
z <- capture.output(fs::dir_tree(path))
z <- z[-1]
w <- lapply(
  z, function(x){
    cat(x, "\n")
  }
)
```

